# Generated by Django 3.1.7 on 2021-03-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20210301_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='num_calle',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
